import mongoose from 'mongoose';

const userSchema = new mongoose.Schema(
  {
    email: { type: String, required: true, unique: true, lowercase: true, trim: true },
    passwordHash: { type: String, required: true },
    role: {
      type: String,
      enum: ['super_admin', 'school_admin', 'driver', 'parent', 'teacher'],
      required: true,
    },
    name: { type: String, required: true, trim: true },
    phone: { type: String, default: '' },
    schoolId: { type: mongoose.Schema.Types.ObjectId, ref: 'School', default: null },
    photoUrl: { type: String, default: '' },
    photoPublicId: { type: String, default: '' },
    aboutMe: { type: String, default: '', trim: true, maxlength: 800 },
    dateOfBirth: { type: Date, default: null },
    gender: { type: String, enum: ['', 'female', 'male', 'other'], default: '' },
    nationality: { type: String, default: '', trim: true },
    idNumber: { type: String, default: '', trim: true },
    yearsOfService: { type: Number, default: 0, min: 0, max: 60 },
    jobTitle: { type: String, default: '', trim: true },
    department: { type: String, default: '', trim: true },
    qualification: { type: String, default: '', trim: true },
    employeeId: { type: String, default: '', trim: true },
    twoFactorEnabled: { type: Boolean, default: false },
    language: { type: String, default: 'English', trim: true },
    theme: { type: String, enum: ['system', 'light', 'dark'], default: 'system' },
    preferences: {
      notifyTrips: { type: Boolean, default: true },
      notifyDiary: { type: Boolean, default: true },
      notifyAnnouncements: { type: Boolean, default: true },
      notifyMessages: { type: Boolean, default: true },
      notifyLeave: { type: Boolean, default: true },
      emailUpdates: { type: Boolean, default: true },
      smsUpdates: { type: Boolean, default: false },
      calendarSync: { type: Boolean, default: false },
      quietHours: { type: Boolean, default: false },
      quietHoursStart: { type: String, default: '22:00' },
      quietHoursEnd: { type: String, default: '06:00' },
      distanceUnit: { type: String, enum: ['km', 'mi'], default: 'km' },
      timeFormat: { type: String, enum: ['12', '24'], default: '12' },
      notifyArrivalTripIds: [{ type: mongoose.Schema.Types.ObjectId, ref: 'Trip' }],
    },
    active: { type: Boolean, default: true },
    lastLoginAt: { type: Date, default: null },
  },
  { timestamps: true }
);

userSchema.methods.toSafeJSON = function toSafeJSON() {
  return {
    id: this._id.toString(),
    email: this.email,
    role: this.role,
    name: this.name,
    phone: this.phone,
    schoolId: this.schoolId?.toString?.() || this.schoolId || null,
    photoUrl: this.photoUrl || '',
    photoPublicId: this.photoPublicId || '',
    aboutMe: this.aboutMe || '',
    dateOfBirth: this.dateOfBirth || null,
    gender: this.gender || '',
    nationality: this.nationality || '',
    idNumber: this.idNumber || '',
    employeeId: this.employeeId || '',
    yearsOfService: this.yearsOfService || 0,
    jobTitle: this.jobTitle || '',
    department: this.department || '',
    qualification: this.qualification || '',
    twoFactorEnabled: this.twoFactorEnabled === true,
    language: this.language || 'English',
    theme: this.theme || 'system',
    preferences: {
      notifyTrips: this.preferences?.notifyTrips !== false,
      notifyDiary: this.preferences?.notifyDiary !== false,
      notifyAnnouncements: this.preferences?.notifyAnnouncements !== false,
      notifyMessages: this.preferences?.notifyMessages !== false,
      notifyLeave: this.preferences?.notifyLeave !== false,
      emailUpdates: this.preferences?.emailUpdates !== false,
      smsUpdates: this.preferences?.smsUpdates === true,
      calendarSync: this.preferences?.calendarSync === true,
      quietHours: this.preferences?.quietHours === true,
      quietHoursStart: this.preferences?.quietHoursStart || '22:00',
      quietHoursEnd: this.preferences?.quietHoursEnd || '06:00',
      distanceUnit: this.preferences?.distanceUnit === 'mi' ? 'mi' : 'km',
      timeFormat: this.preferences?.timeFormat === '24' ? '24' : '12',
      notifyArrivalTripIds: (this.preferences?.notifyArrivalTripIds || []).map((id) => id.toString()),
    },
    active: this.active,
    lastLoginAt: this.lastLoginAt || null,
    createdAt: this.createdAt,
    updatedAt: this.updatedAt || null,
  };
};

export const User = mongoose.model('User', userSchema);
