// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUMlx89quUCzZZneUdPqFHwmg3nHYjoZ8',
    appId: '1:259905986385:web:646942e793b326e67bfd70',
    messagingSenderId: '259905986385',
    projectId: 'tracker2-7f9ce',
    authDomain: 'tracker2-7f9ce.firebaseapp.com',
    storageBucket: 'tracker2-7f9ce.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXcJwBWcH5teifS5xI05CF-U4TjisfWbk',
    appId: '1:259905986385:android:fb29180807938cfe7bfd70',
    messagingSenderId: '259905986385',
    projectId: 'tracker2-7f9ce',
    storageBucket: 'tracker2-7f9ce.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvX0gnL8yLy_XHL0mUm4ZRmuS73gueiTg',
    appId: '1:259905986385:ios:44325b9fe832a40f7bfd70',
    messagingSenderId: '259905986385',
    projectId: 'tracker2-7f9ce',
    storageBucket: 'tracker2-7f9ce.firebasestorage.app',
    iosBundleId: 'com.schoolkids.schoolKidsTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvX0gnL8yLy_XHL0mUm4ZRmuS73gueiTg',
    appId: '1:259905986385:ios:44325b9fe832a40f7bfd70',
    messagingSenderId: '259905986385',
    projectId: 'tracker2-7f9ce',
    storageBucket: 'tracker2-7f9ce.firebasestorage.app',
    iosBundleId: 'com.schoolkids.schoolKidsTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUMlx89quUCzZZneUdPqFHwmg3nHYjoZ8',
    appId: '1:259905986385:web:89a23f8578fcec9f7bfd70',
    messagingSenderId: '259905986385',
    projectId: 'tracker2-7f9ce',
    authDomain: 'tracker2-7f9ce.firebaseapp.com',
    storageBucket: 'tracker2-7f9ce.firebasestorage.app',
  );
}
