/** Steps 1–52 handover test paper. Developer Yes only where this codebase is known to work. */

export const HANDOVER_TITLE = 'School Bus Tracking System';
export const HANDOVER_SUBTITLE = 'Developer Handover & QA Test Paper — Steps 1–52 + Live Tracking';
export const HANDOVER_VERSION = 'v1.0.0';
export const HANDOVER_DATE = '20 Aug 2026';

export const HANDOVER_SECTIONS = [
  {
    heading: '1. Purpose',
    body: 'Consolidated handover for Super Admin (admit schools), School Admin, Driver App, scheduling, live tracking and reporting. This paper lives at /handover.html (web public folder). Stack: Node.js/Express, MongoDB, React (Vite web) and Flutter (driver/parent/teacher). Product version v1.0.0.',
  },
  {
    heading: 'Where to test',
    body: 'Super Admin is /super-admin (login admin@schooltracker.test / password123). School admin is the school-admin site (Dashboard, Students, Transport, Live Tracking, Reports, Settings). Mobile driver is the Flutter driver app. Mobile parent is the Flutter parent app. Some checks need both: admin schedules the trip, driver runs it, parent/admin watch live.',
  },
  {
    heading: 'Super Admin — admit schools',
    body: 'Super Admin creates a school (name, map pin, plan) and optional school-admin account. New schools start pending until Approve. Suspend disables that school’s admin login. Dashboard KPIs and health use live database counts (not mock numbers). Platform invoices/payments stay at KES 0 until an invoice is issued and marked paid.',
  },
  {
    heading: 'Critical trip architecture',
    body: 'Recurring Schedule → Trip Instances → Driver execution → GPS → Check-in → Check-out → Complete. Live Tracking while the instance is active or boarding. Reports after execution. Historical completed trips are not rewritten by schedule edits. Evening: parents are not notified until the child is checked in and the trip is started.',
  },
  {
    heading: 'API boundaries',
    body: 'Super Admin /api/admin/platform/*. School admin /api/admin/trip-schedules, /api/admin/trip-instances, /api/admin/reports, /api/admin/live-tracking. Driver /api/driver/trips and /api/trips. Shared JWT auth and role checks on the server.',
  },
  {
    heading: 'Technology note',
    body: 'The reference package described PostgreSQL. This school tracker uses MongoDB with the same functional relationships (school, student, parent, bus, driver, route, stop, schedule, trip instance, attendance, GPS). Super Admin audit logs are stored in AuditLog.',
  },
  {
    heading: 'Known gaps (do not mark Developer Yes)',
    body: 'No Campus module. School-admin has an Enable audit logs flag but no school-level Audit Logs screen (Super Admin does have Audit Logs and Activity Logs). End Trip with students still checked in is Partial — confirm a hard block with QA. Pickup and drop-off use one home stop per student.',
  },
];

function row(id, area, test, developer, where, procedure, note = '') {
  return { id, area, test, developer, where, procedure, note };
}

export const QA_ROWS = [
  row('s01', 'Step 1', 'Project foundation: apps (web, mobile, server), env, API, deployable layout', 'Yes', 'Server', 'Confirm web, Flutter apps/mobile, and server start with the project .env. No UI click-path.'),
  row('s02', 'Step 2', 'Secure login, logout, password handling, role-based home', 'Yes', 'Web + Mobile', 'Web: open /login. Super Admin (admin@schooltracker.test) lands on /super-admin. School admin, driver, parent, teacher each land on their home. Mobile: Flutter login for school roles. Sign out from the shell.'),
  row('s03', 'Step 3', 'Users & Roles: create and manage school users and roles', 'Yes', 'Web admin', 'School admin → Users & Roles. Create a user, set role, save. Confirm they can log in.'),
  row('s04', 'Step 4', 'School profile and transport configuration', 'Yes', 'Web admin', 'School admin → Settings → School Profile and Transport Settings. Change a field, Save, reload.'),
  row('s05', 'Step 5', 'Multiple campuses as a first-class Campus module', 'No', 'Web admin', 'There is no Campuses menu. Classes exist under More → Classes. Record as gap unless a campus screen is added.', 'Classes exist. A dedicated Campuses screen is not in this build.'),
  row('s06', 'Step 6', 'Academic year / term fields on school settings', 'Yes', 'Web admin', 'Settings → School Profile. Set year/term dates, Save, reload.'),
  row('s07', 'Step 7', 'Classes / grades create, view, edit', 'Yes', 'Web admin', 'More → Classes. Create a class, open it, edit name/grade, save.'),
  row('s08', 'Step 8', 'Student records: create, view, edit', 'Yes', 'Web admin', 'Students. Add a student, open the profile, edit, save. Confirm the list updates.'),
  row('s09', 'Step 9', 'Parent / guardian records', 'Yes', 'Web admin', 'Parents. Create a parent, attach phone/email, open details, edit.'),
  row('s10', 'Step 10', 'Student transport profile (home stop, route, pickup/drop-off)', 'Yes', 'Web admin', 'Students → open a student → transport / stop fields. Set home stop and route, save.'),
  row('s11', 'Step 11', 'Buses: plate, capacity, status', 'Yes', 'Web admin', 'Buses / Vehicles. Add a bus (plate, seats), open details, change status.'),
  row('s12', 'Step 12', 'Drivers: contact, status, assignments', 'Yes', 'Web admin', 'Drivers. Create/open a driver, set phone and status, save.'),
  row('s13', 'Step 13', 'Routes: create, edit, activate/deactivate', 'Yes', 'Web admin', 'Routes. Create a route, open it, toggle active, save.'),
  row('s14', 'Step 14', 'Ordered stops on a route', 'Yes', 'Web admin', 'Routes → open a route (or Stops). Add/reorder pickup stops. Confirm order on the route detail.'),
  row('s15', 'Step 15', 'Assign students to a route / trip', 'Yes', 'Web admin', 'Trip Scheduling: pick students on the schedule, or assign via student transport profile. Confirm they appear on the generated trip.'),
  row('s16', 'Step 16', 'Assign driver to route/schedule', 'Yes', 'Web admin', 'Trip Scheduling → Driver. Save. Open Trips and confirm the instance shows that driver.'),
  row('s17', 'Step 17', 'Assign bus to route/schedule', 'Yes', 'Web admin', 'Trip Scheduling → Bus. Save. Open Trips and confirm the plate on the instance.'),
  row('s18', 'Step 18', 'Student pickup and drop-off stop (home stop)', 'Yes', 'Web admin', 'Student profile → home stop. Morning pickup uses that stop; evening drop-off uses the same home stop after school boarding.'),
  row('s19', 'Step 19', 'Admin transport dashboard with operational numbers', 'Yes', 'Web admin', 'Dashboard (school-admin home). Confirm today’s trip counts and open-live links.'),
  row('s20', 'Step 20', 'Capture GPS during an active (or evening boarding) trip', 'Yes', 'Mobile · driver', 'Driver app: open live for the trip, allow location. Confirm pings continue while driving (and during evening boarding before Start).'),
  row('s21', 'Step 21', 'Map of buses and last known position', 'Yes', 'Web admin', 'Live Tracking. Confirm the bus marker moves or shows last GPS. Open trip details from the side panel.'),
  row('s22', 'Step 22', 'Trip instances with status, route, bus, driver', 'Yes', 'Web admin', 'Trips (Trip Instances). Filter by date/status. Open one instance and check code, route, bus, driver, status.'),
  row('s23', 'Step 23', 'Driver app for assigned trips', 'Yes', 'Mobile · driver', 'Log in as the assigned driver. Home shows current/next trip. Tabs: Check In/Out, My Route, Trips. Web /driver is a fallback, not the phone app.'),
  row('s24', 'Step 24', 'Start trip stores start time and GPS', 'Yes', 'Mobile · driver', 'On a scheduled morning trip: View Trip or Start. After start, Admin → Trips should show startedAt and a GPS point. Evening: check in at least one student first, then Start trip.'),
  row('s25', 'Step 25', 'End trip stores end time and GPS', 'Yes', 'Mobile · driver', 'On the live map Trip tab tap End Trip (or complete from the trip screen). Admin → Trips: status completed, endedAt set.'),
  row('s26', 'Step 26', 'Manual check-in against the Trip ID', 'Yes', 'Mobile · driver', 'Check In/Out. Morning: at a home stop, list every student at that stop, Mark as Picked Up. Evening boarding: list is at School — mark who boarded. Confirm the same Trip ID in Admin → Trips / Attendance.'),
  row('s27', 'Step 27', 'Manual check-out against the Trip ID', 'Yes', 'Mobile · driver', 'After an evening trip is started (or morning arrival at school), Check In/Out in check-out mode. Mark dropped off at the stop. Confirm on the same Trip ID.'),
  row('s28', 'Step 28', 'Student attendance / trip history', 'Yes', 'Web + Mobile', 'Web: Attendance and Reports. Mobile driver: attendance history from Check In/Out. Confirm times match the trip.'),
  row('s29', 'Step 29', 'Parent sees approved live/status for their child', 'Yes', 'Mobile · parent', 'Parent app: after morning pickup or after evening start with the child checked in, open live tracking. Evening scheduled (not started) must not show live to the parent.'),
  row('s30', 'Step 30', 'Transport notifications (start, pickup, complete)', 'Yes', 'Mobile · parent', 'Parent notifications. Morning pickup should notify. Evening: no parent message until the child is checked in and the trip is started.'),
  row('s31', 'Step 31', 'Operational alerts / incidents', 'Yes', 'Web + Mobile', 'Driver: report incident from live/more. Admin: Incidents and Notifications. Confirm the item appears.'),
  row('s32', 'Step 32', 'Admin controls for buses, drivers, routes, stops, students, trips', 'Yes', 'Web admin', 'Walk Buses, Drivers, Routes, Stops, Students, Trip Scheduling, Trips. Create or edit one record in each.'),
  row('s33', 'Step 33', 'Student transport and attendance status on a trip', 'Yes', 'Web admin', 'Trips → open instance. Confirm boarded / pending counts. Live Tracking panel also shows check-in/out counts.'),
  row('s34', 'Step 34', 'Trip history with timestamps, driver, bus, route, GPS', 'Yes', 'Web admin', 'Trips: filter completed. Open a finished instance. Reports → trip instance report for the date range.'),
  row('s35', 'Step 35', 'Driver assigned and completed trip history', 'Yes', 'Web + Mobile', 'Web: Drivers → open driver → trip history. Mobile: driver Trips tab / history.'),
  row('s36', 'Step 36', 'Parent notified after evening check-in + start (not before start)', 'Yes', 'Mobile · driver then parent', 'Evening: driver Open live · check in, mark students, then Start trip. Parent should get “on the evening bus” only after start, only for boarded kids.'),
  row('s37', 'Step 37', 'Backend APIs for core transport entities', 'Yes', 'Server', 'Smoke: login, load dashboard, trips, live-tracking, driver today. Failures show as API errors in the UI.'),
  row('s38', 'Step 38', 'Database entities and relationships', 'Yes', 'Server', 'Create a schedule with bus, driver, students; generate instances. Confirm related records stay linked.', 'MongoDB models, not PostgreSQL tables.'),
  row('s39', 'Step 39', 'Server-side auth and role-protected endpoints', 'Yes', 'Web + Mobile', 'Open an admin URL while logged in as parent — redirect. Driver cannot open school-admin. Logged-out user hits /login.'),
  row('s40', 'Step 40', 'Dedicated audit log of admin/operational changes', 'Partial', 'Web · Super Admin', 'Super Admin → Audit Logs and Activity Logs show live platform changes (admit school, plan, invoices). School Settings still only has an Enable audit logs flag — no school-level history screen.', 'Platform audit works. School-admin change history is not a dedicated screen.'),
  row('s41', 'Step 41', 'Admin reports for trips, students, drivers, buses, routes', 'Yes', 'Web admin', 'Reports & Analytics. Open executive cards and at least one trip/attendance report.'),
  row('s42', 'Step 42', 'Search and filter on admin transport lists', 'Yes', 'Web admin', 'Students, Drivers, Buses, Routes, Trips: use the top search and status/date filters.'),
  row('s43', 'Step 43', 'Validation, API errors, operator feedback', 'Yes', 'Web + Mobile', 'Submit an empty required form on admin. On driver, start an evening trip with zero check-ins — error, not a silent start.'),
  row('s44', 'Step 44', 'Integrated Admin + Driver + GPS + attendance + routes', 'Yes', 'Web + Mobile', 'Admin creates today’s trip → driver runs it with GPS and check-in → admin Live Tracking and Reports show the same Trip ID.', 'Covered in this school’s live runs. Formal automated suite is still for QA.'),
  row('s45', 'Step 45', 'Env, database and deploy configuration present', 'Yes', 'Server', 'Confirm .env (API, Mapbox, Mongo) on server and dart defines / API URL on mobile.'),
  row('s46', 'Step 46', 'Core system and driver app foundation in place', 'Yes', 'Web + Mobile', 'Admin dashboard loads. Driver Home, Check In/Out, and live map load for an assigned driver.'),
  row('s47', 'Step 47', 'Students assigned to classes (and campus if used)', 'Partial', 'Web admin', 'Students / Classes: assign a student to a class. There is no Campus module to assign.', 'Class assignment works. Campus as its own entity is not shipped.'),
  row('s48', 'Step 48', 'Routes, ordered stops, bus and driver assignment', 'Yes', 'Web admin', 'Routes + Stops + Trip Scheduling. Build one full chain: route → stops → bus → driver → students.'),
  row('s49', 'Step 49', 'Students linked to parents for visibility', 'Yes', 'Web admin', 'Student profile: attach parent. Parent login on mobile should list that child.'),
  row('s50a', 'Step 50', 'Schedule types: ONE_TIME, EVERY_DAY, WEEKDAYS, CUSTOM_DAYS', 'Yes', 'Web admin', 'More → Trip Scheduling. Create one of each type, Save, confirm instances on Trips.'),
  row('s50b', 'Step 50', 'Each date generates its own Trip Instance / Trip ID', 'Yes', 'Web admin', 'Weekday schedule → Trips list shows a different trip code per day.'),
  row('s50c', 'Step 50', 'Morning / afternoon / evening, direction, bus, driver, route, students, time', 'Yes', 'Web admin', 'Trip Scheduling form: period, direction (home→school / school→home), time, bus, driver, students. Save.'),
  row('s50d', 'Step 50', 'Multiple morning and afternoon trips for the same bus when conflicts pass', 'Yes', 'Web admin', 'Two morning schedules, same bus, different times. Both instances generate. Overlapping same period should be blocked.'),
  row('s50e', 'Step 50', 'Edit scope: this trip only / this and future / entire series', 'Yes', 'Web admin', 'Trip Scheduling: edit a series, choose scope (this / future / entire), save. Check Trips for what changed.'),
  row('s50f', 'Step 50', 'Date exceptions cancel or override a generated trip', 'Yes', 'Web admin', 'Trip Scheduling → exceptions on a schedule. SKIP a date or override bus/driver. Confirm Trips for that date.'),
  row('s50g', 'Step 50', 'Holiday exclusions cancel generated trips', 'Yes', 'Web admin', 'Trip Scheduling → holidays. Add a holiday date. That day’s scheduled instances should cancel.'),
  row('s50h', 'Step 50', 'Driver and bus overlap / period conflict protection', 'Yes', 'Web admin', 'Assign the same driver (or bus) to two trips in the same period/time. Save should error with the conflicting trip code.'),
  row('s50i', 'Step 50', 'Completed history not silently rewritten by series edits', 'Yes', 'Web admin', 'Complete a past instance, then edit the recurring schedule. That completed trip must keep its old times/status.'),
  row('s51a', 'Step 51', 'Today’s trips lists assigned instances', 'Yes', 'Mobile · driver', 'Driver Home and Trips tab. Every assigned instance for today is listed (not a generic morning flag).'),
  row('s51b', 'Step 51', 'Driver starts/ends the correct Trip ID (morning / afternoon / evening)', 'Yes', 'Mobile · driver', 'Start the morning instance, complete it, then start the evening instance. Admin Trips must show two different IDs.'),
  row('s51c', 'Step 51', 'Cancelled, completed, or already-active trips cannot be started', 'Yes', 'Mobile · driver', 'Try Start on a completed or cancelled card. Try starting a second trip while one is active. Expect a clear error or resume of the active trip.'),
  row('s51d', 'Step 51', 'Only the assigned driver can operate the trip', 'Yes', 'Mobile · driver', 'Log in as a different driver. The trip must not appear as operable. Admin can still view it on web.'),
  row('s51e', 'Step 51', 'Check-in / check-out stored on that Trip ID', 'Yes', 'Mobile · driver', 'Check in student A on trip 1. Complete. On trip 2 the same student starts pending again. Admin attendance is per Trip ID.'),
  row('s51f', 'Step 51', 'Evening: board at school as a full list, then start; parents notified after start', 'Yes', 'Mobile · driver', 'Home → Open live · check in. Check In/Out shows School and every student, not one home stop at a time. Mark who boarded (X if not coming). Start trip. Parents of boarded kids get notified.'),
  row('s51g', 'Step 51', 'Block end-trip while students still have open check-ins', 'Partial', 'Mobile · driver', 'With students still on the bus, tap End Trip. Confirm whether the app blocks or only warns. Pending check-outs show on Home overview.', 'Pending check-outs are shown. Confirm hard block on End Trip with QA.'),
  row('s51h', 'Step 51', 'Start/end GPS stored when the device allows location', 'Yes', 'Mobile · driver', 'Allow location. Start and end a trip. Admin trip detail / live history shows coordinates.'),
  row('s52a', 'Step 52', 'Executive dashboard: scheduled, completed, in progress, cancelled, duration, delay, attendance', 'Yes', 'Web admin', 'Reports & Analytics home. Check the summary cards against Trips for the same date range.'),
  row('s52b', 'Step 52', 'Trip instance report with ID, date, type, direction, bus, driver, route, times, status', 'Yes', 'Web admin', 'Reports → trip instance table. Spot-check one row against Trips.'),
  row('s52c', 'Step 52', 'Student attendance per Trip ID with check-in/out times', 'Yes', 'Web admin', 'Reports / Attendance for a finished trip. Times should match driver check-in/out.'),
  row('s52d', 'Step 52', 'Driver, bus and route performance views', 'Yes', 'Web admin', 'Reports: open driver, bus, and route sections. Numbers should match completed trips.'),
  row('s52e', 'Step 52', 'Schedule exceptions visible with trips', 'Yes', 'Web admin', 'Trips list / scheduling exceptions. A skipped holiday date should not look like a normal completed run.'),
  row('s52f', 'Step 52', 'CSV export for major reports', 'Yes', 'Web admin', 'Reports → export CSV. Open the file and confirm Trip IDs and counts.'),
  row('s52g', 'Step 52', 'Reports are read-only', 'Yes', 'Web admin', 'On Reports, there is no edit/save that changes a trip. After viewing, Trips status is unchanged.'),
  row('lt1', 'Live Tracking', 'Top-level Live Tracking menu, separate from scheduling and reports', 'Yes', 'Web admin', 'Left nav → Live Tracking. Not inside Trip Scheduling or Reports.'),
  row('lt2', 'Live Tracking', 'Buses on in-progress (and boarding) instances on a live map', 'Yes', 'Web admin', 'With a driver on live/boarding, open Live Tracking. The bus is on the map. Completed buses are absent.'),
  row('lt3', 'Live Tracking', 'Bus plate, driver, trip ID, type, direction, route', 'Yes', 'Web admin', 'Select the bus on Live Tracking. Side panel shows plate, driver, trip code, period/direction, route.'),
  row('lt4', 'Live Tracking', 'Start time, last GPS, trip status, check-in/out counts', 'Yes', 'Web admin', 'Same panel: start/boarding time, last update, status, student counts.'),
  row('lt5', 'Live Tracking', 'Select a bus / open current trip details', 'Yes', 'Web admin', 'Click the bus or Open live / trip link. Trip instance or map focus updates.'),
  row('lt6', 'Live Tracking', 'GPS refreshes; last known position if a ping is late', 'Yes', 'Web admin', 'Watch the marker while the driver moves. Pause the driver app briefly — last pin remains until a new ping.'),
  row('lt7', 'Live Tracking', 'Completed trips leave the live map and stay in history/reports', 'Yes', 'Web admin', 'End the trip on the driver app. Live Tracking drops the bus. Trips + Reports still have the instance.'),
  row('nav1', 'Navigation', 'Dashboard, Students, Parents, Classes, Transport, Live Tracking, Reports, Notifications, Users, Settings', 'Yes', 'Web admin', 'Walk the left sidebar. Open each item once.'),
  row('nav2', 'Navigation', 'Transport: Buses, Drivers, Routes, Stops, Trip Scheduling, Trip Instances', 'Yes', 'Web admin', 'Buses, Drivers, Routes, Stops, More → Trip Scheduling, Trips.'),
  row('sa1', 'Super Admin', 'Login as platform Super Admin', 'Yes', 'Web · Super Admin', 'Login admin@schooltracker.test / password123. Lands on Super Admin Dashboard with live school/user/bus/route counts.'),
  row('sa2', 'Super Admin', 'Admit a school with map pin, plan, and school admin', 'Yes', 'Web · Super Admin', 'Schools → Admit a school. Set name, pin on the map, plan, pending status, admin name/email/password. Save. School appears in the table.'),
  row('sa3', 'Super Admin', 'Approve pending school; suspend / reinstate', 'Yes', 'Web · Super Admin', 'Approve a pending school — school admin can then sign in. Suspend — that admin cannot sign in. Reinstate restores access.'),
  row('sa4', 'Super Admin', 'Change subscription plan', 'Yes', 'Web · Super Admin', 'Schools or Subscriptions: change plan (trial/basic/standard/premium). Dashboard donut updates from live counts.'),
  row('sa5', 'Super Admin', 'Issue invoice and mark paid', 'Yes', 'Web · Super Admin', 'Invoices → create for a school → Mark paid. Payments lists it. Dashboard Monthly Revenue uses paid invoices this month (KES 0 until then).'),
  row('sa6', 'Super Admin', 'Users and built-in roles', 'Yes', 'Web · Super Admin', 'Users: search, filter role, disable/enable. Roles & Permissions lists the five built-in roles with live counts (cannot invent a new role without a code change).'),
  row('sa7', 'Super Admin', 'Audit Logs, Activity Logs, System Settings, Health', 'Yes', 'Web · Super Admin', 'Admit a school then open Audit Logs. Activity Logs mix audits and new users/schools. Settings saves platform name. Health shows API, DB ping, heap, sockets — not a fake 4 TB disk.'),
  row('sa8', 'Super Admin', 'Support tickets, announcements, feature requests', 'Yes', 'Web · Super Admin', 'Create a ticket and change status. Publish an announcement (fans out to active/trial school noticeboards). Log a feature request and set planned/done.'),
  row('sa9', 'Super Admin', 'Nav matches platform shell (not under School Settings)', 'Yes', 'Web · Super Admin', 'Sidebar: Dashboard, Schools, Admins, Subscriptions, Payments, Invoices, Users, Roles, Settings, Audit, Activity, Tickets, Announcements, Feature Requests, System Health.'),
];
